[package]
name = "vpn_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"  # Or latest 1.x version
wgctrl = "0.4"     # Or latest 0.4.x version
log = "0.4"